vim9script

language message C
set nocompatible

augroup MyAutoCmd
  autocmd!
augroup END

g:denops#deno = '@deno@'

set runtimepath^=@merged_plugins@

set clipboard=unnamed,unnamedplus

set autoread
set showcmd
set number
set numberwidth=6
set smartindent
set visualbell
set showmatch
set laststatus=2
syntax enable

set expandtab
set tabstop=2
set shiftwidth=2

set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch

set background=light
colorscheme wildcharm

# --------------------------------------------------
#  Skkeleton Configuration
# --------------------------------------------------

def SkkeletonInitialize()
  skkeleton#config({
    sources: ['skk_server']
  })
enddef

inoremap <C-j> <Plug>(skkeleton-enable)

augroup MyAutoCmd
  autocmd User skkeleton-initialize-pre SkkeletonInitialize()
augroup END
