# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  skkdict = {
    pname = "skkdict";
    version = "0a164e6b990c5eb5b59eb7d8789f08865dc2f644";
    src = fetchFromGitHub {
      owner = "skk-dev";
      repo = "dict";
      rev = "0a164e6b990c5eb5b59eb7d8789f08865dc2f644";
      fetchSubmodules = false;
      sha256 = "sha256-xKMtHB54kVSwwwr+v248ewa7dwuavYVmc6KHrZwSdnM=";
    };
    date = "2026-04-12";
  };
  yaskkserv2 = {
    pname = "yaskkserv2";
    version = "08aabbc91a39c67ff2562b29f92c2a274bd0394b";
    src = fetchFromGitHub {
      owner = "wachikun";
      repo = "yaskkserv2";
      rev = "08aabbc91a39c67ff2562b29f92c2a274bd0394b";
      fetchSubmodules = false;
      sha256 = "sha256-3jkB0I+Xp6OA3eQ/Nh6Sqr8DIF2LNpdHFWNLTZN9iYU=";
    };
    date = "2026-10-03";
  };
}
