# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alacritty-theme = {
    pname = "alacritty-theme";
    version = "659d2e1d669cd5722f11e58c44fd45dc26a6ffcd";
    src = fetchFromGitHub {
      owner = "alacritty";
      repo = "alacritty-theme";
      rev = "659d2e1d669cd5722f11e58c44fd45dc26a6ffcd";
      fetchSubmodules = false;
      sha256 = "sha256-jXL0UCLoqiXwihko6F+o247FX4UNFFCOoiA4pZuL/v0=";
    };
    date = "2026-06-12";
  };
}
