# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alacritty-theme = {
    pname = "alacritty-theme";
    version = "ab88d5a80d676b5dc6157e91aba8067f2078dc94";
    src = fetchFromGitHub {
      owner = "alacritty";
      repo = "alacritty-theme";
      rev = "ab88d5a80d676b5dc6157e91aba8067f2078dc94";
      fetchSubmodules = false;
      sha256 = "sha256-pfpujHc6+shftp+idGOA70NXKR8ASIIbdNb4eMCXb7U=";
    };
    date = "2026-09-11";
  };
}
