# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alacritty-theme = {
    pname = "alacritty-theme";
    version = "2749b407b597790e6f08b218c2bc2acdf66210a0";
    src = fetchFromGitHub {
      owner = "alacritty";
      repo = "alacritty-theme";
      rev = "2749b407b597790e6f08b218c2bc2acdf66210a0";
      fetchSubmodules = false;
      sha256 = "sha256-F8ye16jhfldsyxcOqxVS0PNecVcQcAPnEahDKS4PGwE=";
    };
    date = "2026-05-01";
  };
}
