# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  denops-vim = {
    pname = "denops-vim";
    version = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
      fetchSubmodules = false;
      sha256 = "sha256-lj8yjZrwE9GfNPDIpH4tCI4TTJHkYRlFFCTdqMqWtZg=";
    };
    date = "2026-03-22";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "770b265dd115dba96ea5314642e35764654ef08f";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "770b265dd115dba96ea5314642e35764654ef08f";
      fetchSubmodules = false;
      sha256 = "sha256-Gsl/LqUY8szRqYLnDVyDOIDCw+cisoKsS5Fl1zQ+unM=";
    };
    date = "2026-05-05";
  };
}
