# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  denops-vim = {
    pname = "denops-vim";
    version = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "1df7a022d6e9cb3f6a3db43235e0f174ccd79e03";
      fetchSubmodules = false;
      sha256 = "sha256-lj8yjZrwE9GfNPDIpH4tCI4TTJHkYRlFFCTdqMqWtZg=";
    };
    date = "2026-03-22";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
      fetchSubmodules = false;
      sha256 = "sha256-OhHlG3ngNbvUSNqS/MFJpYI/cfbkxSxTPo8EiSwW/MU=";
    };
    date = "2026-04-02";
  };
}
