# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  denops-vim = {
    pname = "denops-vim";
    version = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
      fetchSubmodules = false;
      sha256 = "sha256-z9FadzT6Y7vFLLdpFR/Ti/FVPGwED4uEkiNZZOkSkqU=";
    };
    date = "2026-05-15";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "412826823ec17503bc10f7c590dd4d9f9b0be4fa";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "skkeleton";
      rev = "412826823ec17503bc10f7c590dd4d9f9b0be4fa";
      fetchSubmodules = false;
      sha256 = "sha256-6mbPJJ73vSjZPyYg292EbUEDPBz5qQoZs60+Q1s3jeQ=";
    };
    date = "2026-07-26";
  };
  vim-lsp = {
    pname = "vim-lsp";
    version = "bbffa60cb08a6a2d67e2086a89699ab00a084fe9";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "vim-lsp";
      rev = "bbffa60cb08a6a2d67e2086a89699ab00a084fe9";
      fetchSubmodules = false;
      sha256 = "sha256-eExLKs0FULF2z3Ox4AsnMxyaFTHy3CL+3tUJOm/v2RE=";
    };
    date = "2026-09-02";
  };
  vim-lsp-settings = {
    pname = "vim-lsp-settings";
    version = "c61a46e4cc31ec58159d3908e5b1f1003923990b";
    src = fetchFromGitHub {
      owner = "mattn";
      repo = "vim-lsp-settings";
      rev = "c61a46e4cc31ec58159d3908e5b1f1003923990b";
      fetchSubmodules = false;
      sha256 = "sha256-7DW9ONktKXIxWM08Xok4RBhnEPnRrVCDKpkH9LKMX8k=";
    };
    date = "2026-09-05";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
    src = fetchFromGitHub {
      owner = "LnL7";
      repo = "vim-nix";
      rev = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
      fetchSubmodules = false;
      sha256 = "sha256-Hmn8EVlvMQnQF8COeb89cgl5+A83kagOjGsmvm5WNoE=";
    };
    date = "2025-02-01";
  };
}
