# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  denops-vim = {
    pname = "denops-vim";
    version = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
      fetchSubmodules = false;
      sha256 = "sha256-z9FadzT6Y7vFLLdpFR/Ti/FVPGwED4uEkiNZZOkSkqU=";
    };
    date = "2026-05-15";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "770b265dd115dba96ea5314642e35764654ef08f";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "770b265dd115dba96ea5314642e35764654ef08f";
      fetchSubmodules = false;
      sha256 = "sha256-Gsl/LqUY8szRqYLnDVyDOIDCw+cisoKsS5Fl1zQ+unM=";
    };
    date = "2026-05-05";
  };
  vim-lsp = {
    pname = "vim-lsp";
    version = "474c656659b5fb51eec6770309e0211c8aa49b5b";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "vim-lsp";
      rev = "474c656659b5fb51eec6770309e0211c8aa49b5b";
      fetchSubmodules = false;
      sha256 = "sha256-ZMqeuTKyQAknqXA4IvNCzgumcrafu0sLNp3ZFwQ6kj4=";
    };
    date = "2026-04-19";
  };
  vim-lsp-settings = {
    pname = "vim-lsp-settings";
    version = "1558bbaba4cbb593901e3dfc4d0f1a0cd212b09c";
    src = fetchFromGitHub {
      owner = "mattn";
      repo = "vim-lsp-settings";
      rev = "1558bbaba4cbb593901e3dfc4d0f1a0cd212b09c";
      fetchSubmodules = false;
      sha256 = "sha256-wMF4y4eMz7UR50GpBvStDsQ0SpKUt48tll6rqEr6AHY=";
    };
    date = "2026-05-21";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
    src = fetchFromGitHub {
      owner = "LnL7";
      repo = "vim-nix";
      rev = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
      fetchSubmodules = false;
      sha256 = "sha256-Hmn8EVlvMQnQF8COeb89cgl5+A83kagOjGsmvm5WNoE=";
    };
    date = "2025-02-01";
  };
}
