# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  denops-vim = {
    pname = "denops-vim";
    version = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops.vim";
      rev = "e82c5a94ca1154b05c9d74d6f6f58c9991b1424f";
      fetchSubmodules = false;
      sha256 = "sha256-z9FadzT6Y7vFLLdpFR/Ti/FVPGwED4uEkiNZZOkSkqU=";
    };
    date = "2026-05-15";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "a963b714a34853fb3510550c3d92b49f9309388e";
    src = fetchFromGitHub {
      owner = "Warashi";
      repo = "skkeleton";
      rev = "a963b714a34853fb3510550c3d92b49f9309388e";
      fetchSubmodules = false;
      sha256 = "sha256-OUjSGvi1kc5pOLBMx7BCfwgf0YmCMqestW7QGdeqDLY=";
    };
    date = "2026-06-26";
  };
  vim-lsp = {
    pname = "vim-lsp";
    version = "474c656659b5fb51eec6770309e0211c8aa49b5b";
    src = fetchFromGitHub {
      owner = "prabirshrestha";
      repo = "vim-lsp";
      rev = "474c656659b5fb51eec6770309e0211c8aa49b5b";
      fetchSubmodules = false;
      sha256 = "sha256-ZMqeuTKyQAknqXA4IvNCzgumcrafu0sLNp3ZFwQ6kj4=";
    };
    date = "2026-04-19";
  };
  vim-lsp-settings = {
    pname = "vim-lsp-settings";
    version = "22d06c9e4b620d5c2f055aec590dec6d383e5316";
    src = fetchFromGitHub {
      owner = "mattn";
      repo = "vim-lsp-settings";
      rev = "22d06c9e4b620d5c2f055aec590dec6d383e5316";
      fetchSubmodules = false;
      sha256 = "sha256-LiWvL9QpZFPUH+Uek19ce6/e8B6uATmje/emUvyLWJk=";
    };
    date = "2026-07-16";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
    src = fetchFromGitHub {
      owner = "LnL7";
      repo = "vim-nix";
      rev = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
      fetchSubmodules = false;
      sha256 = "sha256-Hmn8EVlvMQnQF8COeb89cgl5+A83kagOjGsmvm5WNoE=";
    };
    date = "2025-02-01";
  };
}
