# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  epkgs = {
    pname = "epkgs";
    version = "bff1fa84ba21ad84e096a495beaae821babea6d0";
    src = fetchFromGitHub {
      owner = "emacsmirror";
      repo = "epkgs";
      rev = "bff1fa84ba21ad84e096a495beaae821babea6d0";
      fetchSubmodules = false;
      sha256 = "sha256-MSaPGisZBJaBTRUXkkG574pPlktGyAoCM5tGqg5N3UM=";
    };
    date = "2026-06-26";
  };
  gnu-elpa = {
    pname = "gnu-elpa";
    version = "fcf738c3547216d700e1f67a2e1830ed2acba981";
    src = fetchFromGitHub {
      owner = "elpa-mirrors";
      repo = "elpa";
      rev = "fcf738c3547216d700e1f67a2e1830ed2acba981";
      fetchSubmodules = false;
      sha256 = "sha256-xmX4v8LmAU6v0cbNx/oA8bci17JCtEreUCMWuJAFxK8=";
    };
    date = "2026-06-27";
  };
  melpa = {
    pname = "melpa";
    version = "14479a3c538fed8b2c904ed59377c3c3a76c08db";
    src = fetchFromGitHub {
      owner = "melpa";
      repo = "melpa";
      rev = "14479a3c538fed8b2c904ed59377c3c3a76c08db";
      fetchSubmodules = false;
      sha256 = "sha256-+M0K4AUq1ApMEi8k1LQg3iPfhAPZaVqME+kaJjbTIXE=";
    };
    date = "2026-06-28";
  };
  nongnu-elpa = {
    pname = "nongnu-elpa";
    version = "2e12d173f9e329f1a37c07a4a84fdbaaff12d245";
    src = fetchFromGitHub {
      owner = "elpa-mirrors";
      repo = "nongnu";
      rev = "2e12d173f9e329f1a37c07a4a84fdbaaff12d245";
      fetchSubmodules = false;
      sha256 = "sha256-4cTfnlfiz8O0ii0GWdHVqw1bJUreeCZY/eVhhq3PQGY=";
    };
    date = "2026-06-27";
  };
}
