# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  epkgs = {
    pname = "epkgs";
    version = "98872b60db535d9d45801d06f7e1b76949769d90";
    src = fetchFromGitHub {
      owner = "emacsmirror";
      repo = "epkgs";
      rev = "98872b60db535d9d45801d06f7e1b76949769d90";
      fetchSubmodules = false;
      sha256 = "sha256-/A7VnSfwebL5Ytqdn7gyAXuDQZw2bQT3lxV5DVruCk4=";
    };
    date = "2026-08-24";
  };
  gnu-elpa = {
    pname = "gnu-elpa";
    version = "0d7d3f5281ba72d994b68a02f363e6e619ecce59";
    src = fetchFromGitHub {
      owner = "elpa-mirrors";
      repo = "elpa";
      rev = "0d7d3f5281ba72d994b68a02f363e6e619ecce59";
      fetchSubmodules = false;
      sha256 = "sha256-gMB0uqmBs9X0rqsqeoAnYz4IKE/G+8MuEBI79fTMK/g=";
    };
    date = "2026-08-26";
  };
  melpa = {
    pname = "melpa";
    version = "bc5448d0a8b2d9d618db699525e277cb24981054";
    src = fetchFromGitHub {
      owner = "melpa";
      repo = "melpa";
      rev = "bc5448d0a8b2d9d618db699525e277cb24981054";
      fetchSubmodules = false;
      sha256 = "sha256-hNZ77xFkqHHHYLl1NNKy3nwvh5oDprdln6SzH8MMZeg=";
    };
    date = "2026-08-30";
  };
  nongnu-elpa = {
    pname = "nongnu-elpa";
    version = "d3cba693ba67ab9d41bfa1df06ce8738d3c1292c";
    src = fetchFromGitHub {
      owner = "elpa-mirrors";
      repo = "nongnu";
      rev = "d3cba693ba67ab9d41bfa1df06ce8738d3c1292c";
      fetchSubmodules = false;
      sha256 = "sha256-gz0l0RlO9eJGdAvpgnDw8N900luAG4SMWSF9rA2ctNs=";
    };
    date = "2026-08-24";
  };
}
