# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  epkgs = {
    pname = "epkgs";
    version = "d3db51b809f6bbf5e7ff19fe22e45702d1a626ad";
    src = fetchFromGitHub {
      owner = "emacsmirror";
      repo = "epkgs";
      rev = "d3db51b809f6bbf5e7ff19fe22e45702d1a626ad";
      fetchSubmodules = false;
      sha256 = "sha256-X3QT4UKHUx2gJGZ9HfaZIw0p6ik+bLlOd4MdRjM8KT0=";
    };
    date = "2026-09-28";
  };
  gnu-elpa = {
    pname = "gnu-elpa";
    version = "2129d367ed03c8e5d6e3cedca1c4224b62d03eb6";
    src = fetchFromGitHub {
      owner = "elpa-mirrors";
      repo = "elpa";
      rev = "2129d367ed03c8e5d6e3cedca1c4224b62d03eb6";
      fetchSubmodules = false;
      sha256 = "sha256-6+FpcgrScg5uIM+PFfNOK7Da6UTg9GagU+q3JNbJbc8=";
    };
    date = "2026-09-22";
  };
  melpa = {
    pname = "melpa";
    version = "4810edecf4ab88be3c83b0f82047e651a30103f9";
    src = fetchFromGitHub {
      owner = "melpa";
      repo = "melpa";
      rev = "4810edecf4ab88be3c83b0f82047e651a30103f9";
      fetchSubmodules = false;
      sha256 = "sha256-Yz2Njoj22115FAcD3uOAUMLYnod9lI3r8bOMHx56VRs=";
    };
    date = "2026-10-01";
  };
  nongnu-elpa = {
    pname = "nongnu-elpa";
    version = "81c81ac6695e6732344061ac3a041a416c9f6fcb";
    src = fetchFromGitHub {
      owner = "elpa-mirrors";
      repo = "nongnu";
      rev = "81c81ac6695e6732344061ac3a041a416c9f6fcb";
      fetchSubmodules = false;
      sha256 = "sha256-dg6iZ+zVRyEOvS71vR/jay6+10HCI6qob1XUchk+m+U=";
    };
    date = "2026-10-01";
  };
}
