# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fish-fzf-bd = {
    pname = "fish-fzf-bd";
    version = "fcbe9f6a75510365638dc6f790544c55ecb0ec3b";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "fish-fzf-bd";
      rev = "fcbe9f6a75510365638dc6f790544c55ecb0ec3b";
      fetchSubmodules = false;
      sha256 = "sha256-NAErU+F7CTf0wOfR1zfxw2TRBLPIHe5QDjEhyjCNLJE=";
    };
    date = "2025-01-27";
  };
  fish-ghq-fzf = {
    pname = "fish-ghq-fzf";
    version = "9798eadadda71c3cb43502f88cfce1f9521ee185";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "fish-ghq-fzf";
      rev = "9798eadadda71c3cb43502f88cfce1f9521ee185";
      fetchSubmodules = false;
      sha256 = "sha256-64y5nTQsdz8Qyn0VjEtfI4FvTMjF5XVYW7yTsrkIS30=";
    };
    date = "2025-01-27";
  };
}
