# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mattpocock-skills = {
    pname = "mattpocock-skills";
    version = "448d0adee7cb797db5a2ad278e9e8d6c874e12af";
    src = fetchFromGitHub {
      owner = "mattpocock";
      repo = "skills";
      rev = "448d0adee7cb797db5a2ad278e9e8d6c874e12af";
      fetchSubmodules = false;
      sha256 = "sha256-FzoicELpTDKpiHhXWC3YmBfReW/B1M27LrJykh5x5aQ=";
    };
    date = "2026-06-29";
  };
}
