# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mattpocock-skills = {
    pname = "mattpocock-skills";
    version = "0986ebaf5d29e812162702b2633a2942c30200d2";
    src = fetchFromGitHub {
      owner = "mattpocock";
      repo = "skills";
      rev = "0986ebaf5d29e812162702b2633a2942c30200d2";
      fetchSubmodules = false;
      sha256 = "sha256-u2kFjowk/EvlL4J4WIAddrdeVJPZK0oXKxUfGfxqtz0=";
    };
    date = "2026-08-05";
  };
}
