# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mattpocock-skills = {
    pname = "mattpocock-skills";
    version = "5d78bd0903420f97c791f834201e550c765699f8";
    src = fetchFromGitHub {
      owner = "mattpocock";
      repo = "skills";
      rev = "5d78bd0903420f97c791f834201e550c765699f8";
      fetchSubmodules = false;
      sha256 = "sha256-efsb/AXAmEvcjoknbExBeEHFB28o2c2Nk8muWwNNQFQ=";
    };
    date = "2026-06-25";
  };
}
