# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  vim = {
    pname = "vim";
    version = "16f562b4e54ed13e54fac9a7bf27feff6beca345";
    src = fetchFromGitHub {
      owner = "vim";
      repo = "vim";
      rev = "16f562b4e54ed13e54fac9a7bf27feff6beca345";
      fetchSubmodules = false;
      sha256 = "sha256-6WKb5TrIoypOfFf3vfDaVK6Rl2CRkU4M+kIMON32VM4=";
    };
    date = "2026-07-20";
  };
}
