# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  vim = {
    pname = "vim";
    version = "975e191dc817d8d00abca7197c4529a417c2f805";
    src = fetchFromGitHub {
      owner = "vim";
      repo = "vim";
      rev = "975e191dc817d8d00abca7197c4529a417c2f805";
      fetchSubmodules = false;
      sha256 = "sha256-e4B0JDpxC/uTF+4mbsh0/QiajIfJ0NlOeUkyZJcgbcw=";
    };
    date = "2026-07-23";
  };
}
