# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  vim = {
    pname = "vim";
    version = "3fa4da4acb194660b7f44bba027af9f2120c27fe";
    src = fetchFromGitHub {
      owner = "vim";
      repo = "vim";
      rev = "3fa4da4acb194660b7f44bba027af9f2120c27fe";
      fetchSubmodules = false;
      sha256 = "sha256-Vh0W3I4ED+gsIPdB5CCxa8rP89rtMOMq0bBvI35EqWc=";
    };
    date = "2026-06-29";
  };
}
