name: Update Nix Flake Inputs

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 1 * * *"
      timezone: "Asia/Tokyo"

permissions: {}

jobs:
  list-flake-inputs:
    runs-on: ubuntu-slim
    outputs:
      inputs: ${{ steps.list-flake-inputs.outputs.inputs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          show-progress: false
      - name: List flake inputs
        id: list-flake-inputs
        run: echo "inputs=$(jq -c '.nodes[.root].inputs | keys' flake.lock)" >> $GITHUB_OUTPUT

  update-flake-inputs:
    runs-on: ubuntu-slim
    needs: list-flake-inputs
    strategy:
      matrix:
        input: ${{ fromJson(needs.list-flake-inputs.outputs.inputs) }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          extra_nix_config: |
            accept-flake-config = true
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ vars.NIX_UPDATER_CLIENT_ID }}
          private-key: ${{ secrets.NIX_UPDATER_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true
          show-progress: false
      - name: Prepare git
        env:
          TARGET_INPUT: ${{ matrix.input }}
        run: |
          git config user.name "warashi-nix-updater[bot]"
          git config user.email "265781387+warashi-nix-updater[bot]@users.noreply.github.com"
          git switch -c "update-flake-inputs-${TARGET_INPUT}"
      - name: Update flake inputs
        env:
          TARGET_INPUT: ${{ matrix.input }}
        run: nix flake update "${TARGET_INPUT}"
      - name: Commit and create pull request
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: update flake inputs (${TARGET_INPUT})"
            git push --force origin HEAD
            gh pr create --title "chore: update flake inputs (${TARGET_INPUT})" --body "This PR updates the flake inputs (${TARGET_INPUT}) to their latest versions." || echo "PR is already open"
            gh pr merge --auto --squash || echo "Failed to merge PR"
          else
            echo "No changes to commit"
          fi
